In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from scipy.spatial import distance


In [ ]:
data=pd.read_csv('anime.csv')

In [ ]:
data=data[data['genre']!='Hentai']

In [ ]:
data.head()

anime_id                              name  \
0     32281                    Kimi no Na wa.   
1      5114  Fullmetal Alchemist: Brotherhood   
2     28977                          Gintama°   
3      9253                       Steins;Gate   
4      9969                     Gintama&#039;   

                                               genre   type episodes  rating  \
0               Drama, Romance, School, Supernatural  Movie        1    9.37   
1  Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64    9.26   
2  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.25   
3                                   Sci-Fi, Thriller     TV       24    9.17   
4  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.16   

   members  
0   200630  
1   793665  
2   114262  
3   673572  
4   151266

In [ ]:
# we want to know all the genres of the animes

In [ ]:
genre=data['genre'].values
print(genre)
print(len(genre))

['Drama, Romance, School, Supernatural'
 'Action, Adventure, Drama, Fantasy, Magic, Military, Shounen'
 'Action, Comedy, Historical, Parody, Samurai, Sci-Fi, Shounen' ...
 'Comedy, Hentai' 'Hentai, Slice of Life' 'Demons, Hentai, Supernatural']
11471


In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11471 entries, 0 to 12285
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   anime_id  11471 non-null  int64  
 1   name      11471 non-null  object 
 2   genre     11409 non-null  object 
 3   type      11446 non-null  object 
 4   episodes  11471 non-null  object 
 5   rating    11248 non-null  float64
 6   members   11471 non-null  int64  
dtypes: float64(1), int64(2), object(4)
memory usage: 716.9+ KB


In [ ]:
lis=[]
for i in genre:
    i=str(i)
    for p in i.split(','):
        if p not in lis:
            lis.append(p)

In [ ]:
len(lis)


['Drama', ' Romance', ' School', ' Supernatural', 'Action', ' Adventure', ' Drama', ' Fantasy', ' Magic', ' Military', ' Shounen', ' Comedy', ' Historical', ' Parody', ' Samurai', ' Sci-Fi', 'Sci-Fi', ' Thriller', 'Comedy', ' Sports', ' Super Power', ' Space', ' Slice of Life', ' Mecha', 'Adventure', ' Music', ' Mystery', ' Seinen', 'Fantasy', ' Martial Arts', ' Vampire', ' Shoujo', ' Horror', ' Police', ' Psychological', 'Mystery', 'Psychological', ' Demons', 'Ecchi', ' Josei', 'Josei', 'Military', 'Romance', ' Shounen Ai', ' Game', 'Demons', ' Ecchi', 'Dementia', ' Harem', 'Music', 'Game', ' Cars', ' Dementia', 'Cars', 'Mecha', 'Horror', 'School', ' Kids', 'Historical', 'Kids', ' Shoujo Ai', 'Shounen', 'Shoujo', 'Magic', 'Harem', 'Martial Arts', 'Sports', 'Slice of Life', 'Seinen', 'nan', 'Parody', 'Police', 'Thriller', 'Supernatural', 'Samurai', 'Super Power', 'Vampire', 'Space', ' Yaoi', ' Hentai', 'Hentai', ' Yuri', 'Yaoi']


In [ ]:
dic={}


In [ ]:
t=[]
for i in genre:
    for j in lis:
        dic[j]=0
    i=str(i)
    for p in i.split(','):
        dic[p]+=1
    t.append(list(dic.values()))



In [ ]:
len(t[0])

[[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [ ]:
X=np.array(t)
print(X)

[[1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
# input 1 is the anime name
# input 2 is the number of search result you want
s=input('Enter the anime you like and we will find more like those for you  :')
num=int(input('Please enter the number of recommendations you want:'))
name=data['name'].values
print(name)
for i in range(len(name)):
    name[i]=name[i].lower()
s=s.lower()
h=-1
for i in range(len(name)):
    if s in name[i]:
        h=i
        break
imp=[]
if h==-1:
    print('Sorry No match found :(')
else:
    for i in range(len(t)):
        if i==h:
            continue
        else:
            if len(imp)<num:
                imp.append([distance.euclidean(t[i], t[h]),t[i],i])
            else:
                imp.sort()
                if imp[num-1][0]>distance.euclidean(t[i],t[h]):
                    del imp[num-1]
                    imp.append([distance.euclidean(t[i],t[h]),t[i],i])

    name=data['name'].values
    print('The anime recommended for you are :')
    count=0
    for i in imp:
        count+=1
        print(count,'. ',name[i[2]])


Enter the anime you like and we will find more like those for you  :death note
Please enter the number of recommendations you want:4
['kimi no na wa.' 'fullmetal alchemist: brotherhood' 'gintama°' ...
 'original video romance animation' 'pink no curtain' 'taimanin asagi 3']
The anime recommended for you are :
1 .  death note rewrite
2 .  higurashi no naku koro ni kai
3 .  jigoku shoujo mitsuganae
4 .  yakushiji ryouko no kaiki jikenbo
